services:
  standup-summarizer:
    build: .
    volumes:
      - ./:/app
      - ./output:/app/output
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - WHISPER_MODEL=base
      - OUTPUT_DIRECTORY=/app/output
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    ports:
      - "8000:8000"