# services:
#   standup-summarizer:
#     build: .
#     volumes:
#       - ./:/app
#       - ./output:/app/output
#     environment:
#       - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
#       - WHISPER_MODEL=base
#       - OUTPUT_DIRECTORY=/app/output
#       - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
#       - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
#     ports:
#       - "8000:8000"


services:
  standup-summarizer:
    build: .
    volumes:
      - ./:/app
      - ./output:/app/output
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - WHISPER_MODEL=base
      - OUTPUT_DIRECTORY=/app/output
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    ports:
      - "8000:8000"

  frontend:
    image: node:18-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_URL=http://localhost:8000
    command: sh -c "npm install && npm run serve"
    depends_on:
      - standup-summarizer