version: '3.8'

services:
  standup-summarizer:
    build: .
    volumes:
      - ./:/app
      - ./output:/app/output
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - WHISPER_MODEL=base
      - OUTPUT_DIRECTORY=/app/output
    # For audio recording, you'll need to give Docker access to your audio device
    # Uncommenting this will allow Docker to access your host's audio device (Linux only)
    # devices:
    #  - /dev/snd:/dev/snd